// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGCxifZy97uAcNjNQL34bot_VQmCh_6kk',
    appId: '1:531676871418:web:fce95125f54988560da743',
    messagingSenderId: '531676871418',
    projectId: 'unibuddy-fd6c0',
    authDomain: 'unibuddy-fd6c0.firebaseapp.com',
    storageBucket: 'unibuddy-fd6c0.firebasestorage.app',
    measurementId: 'G-V11X527V62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7qnTnmF-lzaWbw_V2285rOj7g-1hG5OE',
    appId: '1:531676871418:android:5a3dc8a1c6ec683e0da743',
    messagingSenderId: '531676871418',
    projectId: 'unibuddy-fd6c0',
    storageBucket: 'unibuddy-fd6c0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1azK8Wt8tjO-6Ae9k4LXqEAOpsZTG_dw',
    appId: '1:531676871418:ios:98ea8bad2a2bae040da743',
    messagingSenderId: '531676871418',
    projectId: 'unibuddy-fd6c0',
    storageBucket: 'unibuddy-fd6c0.firebasestorage.app',
    iosBundleId: 'com.example.unibuddy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1azK8Wt8tjO-6Ae9k4LXqEAOpsZTG_dw',
    appId: '1:531676871418:ios:98ea8bad2a2bae040da743',
    messagingSenderId: '531676871418',
    projectId: 'unibuddy-fd6c0',
    storageBucket: 'unibuddy-fd6c0.firebasestorage.app',
    iosBundleId: 'com.example.unibuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGCxifZy97uAcNjNQL34bot_VQmCh_6kk',
    appId: '1:531676871418:web:89743bca6f8f06ca0da743',
    messagingSenderId: '531676871418',
    projectId: 'unibuddy-fd6c0',
    authDomain: 'unibuddy-fd6c0.firebaseapp.com',
    storageBucket: 'unibuddy-fd6c0.firebasestorage.app',
    measurementId: 'G-9L3MEELM83',
  );
}
